default_platform(:ios)

platform :ios do
  desc "Upload signed IPA to TestFlight"
  lane :upload do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"],
    )

    ipa_glob = File.join(ENV.fetch("GITHUB_WORKSPACE"), "build/ios/ipa/*.ipa")
    ipa_path = Dir.glob(ipa_glob).first
    UI.user_error!("IPA not found under #{ipa_glob}") if ipa_path.nil?

    upload_to_testflight(
      ipa: ipa_path,
      skip_waiting_for_build_processing: true,
    )
  end

  desc "Install Codesign and a Provisioning Profile"
  lane :setup do
    setup_ci

    match(
      type: "appstore",
      readonly: true,
    )
  end
end
