default_platform(:android)

platform :android do
  desc "Upload AAB to Play Store internal track"
  lane :upload do
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "draft",
    )
  end
end
